name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: wasm32-wasip1
      - run: cargo build --target wasm32-wasip1 --release
      - run: cargo test --no-default-features
